name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - run: ./mvnw package
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/maven-gav-checker-*-runner"
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        makeLatest: true
        prerelease: true
