name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - run: ./mvnw -Pjar package
    - run: ./mvnw -Pnative package
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/maven-gav-checker-*-runner,target/maven-gav-checker-*-runner.jar"
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        makeLatest: true
        prerelease: true
